// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
// import {SessionProvider} from 'next-auth/react'
// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SessionProvider>
//         {children}
//         </SessionProvider>
//         </body>
//     </html>
//   )
// }

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
// import {SessionProvider} from 'next-auth/react'
// import {Session} from 'next-auth'
// const inter = Inter({ subsets: ['latin'] })
// interface Props {
//   session: Session | null
//   children: React.ReactNode
// }
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// const RootLayout: React.FC<Props>=({children, session})=> {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SessionProvider session={session}>
//           {children}
//         </SessionProvider>
        
//         </body>
//     </html>
//   )
// }
// export default RootLayout
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from './provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextAuthProvider>
            {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}